language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install numpy
  - pip install lesscpy
  - python setup.py build_ext --inplace
# command to run tests
script: 
    - nosetests -s tests/test_themes.py
